version: 2.1
orbs:
  k6io: k6io/test@1.1.0
workflows:
  load_test:
    jobs:
      - k6io/test:
          cloud: true
          arguments: --env K6_CLOUD_PROJECT_ID=$K6_CLOUD_PROJECT_ID K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN
          script: loadtests/performance-test.js
      - k6io/test:
          cloud: true
          token: K6_CLOUD_TOKEN
          script: k6 login cloud --token K6_CLOUD_TOKEN